### ISSUE TITLE
Unicode problem with json::reader

### ISSUE THREAD

**Issue by BobMcKay** [open-source-parsers/jsoncpp#1112]
Am I doing something wrong or is that a bug?

```
Json::Value v;
v["data"] = "ä ö ü Ä Ö Ü";
std::string stds = v["data"].asString();
OutputDebugString( stds.data() );
//ä ö ü Ä Ö Ü
// as expected...

// Now, i write it in a string...	
Json::FastWriter writer;
std::string  s = writer.write( v );
OutputDebugString( s.data() );
// {"data":"\u4836 \ufffd \u0120\u05a0\ufffd"}

// and back again...
Json::Reader reader;
Json::Value r;
reader.parse( s, r );

// we look at the 'data'
stds = r["data"].asString();
OutputDebugString( stds.data() );
// There should contain ä ö ü Ä Ö Ü
// but: ä ¶ ï¿½ Ä Ö ï¿½

// if we write the parsed data again...
std::string s2 = writer.write( r );
OutputDebugString( s2.data() );
// {"data":"\u4836 \ufffd \u0120\u05a0\ufffd"}
// the same like the origin data
```
Any ideas?

**Comment by dota17** [comment]
1. These data's escaped Unicode are wrong, actually, there are `\uE4 \uF6 \uFC \uC4 \uD6 \uDC`
2. if you use `strcmp()` to compare `v["data"].asString().data()` and `r["data"].asString().data()`.

so I don't think this is a bug.

**Comment by BillyDonahue** [comment]
I'm confused about this report. I don't understand where the values like \ufffd came from.

@dota17, there are no 2-digit \u escapes. They always have 4 hex digits \uxxxx.
So it's "\u00e4 \u00f6 \u00fC \u00c4 \u00d6 \u00dc".
The xxxx are the 16-bit unicode numeric value, not its utf-8 encoding.

I still can't explain why OutputDebugString of s.data() in his example yielded this:
{"data":"\u4836 \ufffd \u0120\u05a0\ufffd"}
Those are already corrupted. There are not \ufffd etc in the input.

@dota17, I can't figure out a reason backing your claim about strmp() equality of the `v` and `r` strings. It looks like 


But I have no idea where that assertion came from. It could be an artifact of the collection mechanism. It would be better to have a test case in a fork branch somewhere so I can see what the real problem was. @BobMcKay can you provide a repro test case in github somewhere?

@BobMcKay you *are* doing something a little wrong by using Reader instead of CharReader. Reader is deprecated.

**Comment by dota17** [comment]
Yes, I wrote it wrong, I should not omit the preceding 0.
> // we look at the 'data'
stds = r["data"].asString();
OutputDebugString( stds.data() );
// There should contain ä ö ü Ä Ö Ü
// but: ä ¶ ï¿½ Ä Ö ï¿½

I tested them with `strcmp(v["data"].asString().data(), r["data"].asString().data())`, the result is equal.
so, I don't know why that is `ä ¶ ï¿½ Ä Ö ï¿½`, Anyway, some of the information @BobMcKay  provided is not correct.

**Comment by dota17** [comment]
@BobMcKay , can you ensure your console is encoded as UTF-8?
When the charset is different, it will be shown as other char,  like `ä ¶ ï¿½ Ä Ö ï¿½`.
And I had made a testcase, when the console is encoded as GBK, it was `盲 枚 眉 脛 脰 脺`.

**Comment by cdunn2001** [comment]
The older Reader/Writer are known to have some minor problems. Please use `CharReader`/ `StreamWriter`, which we can maintain because we do not need to worry so much about its binary compatibiity.

(We might accept a bug-fix for old `FastWriter`, but not if it breaks binary compatibility.)
