### ISSUE TITLE
Excessive memory allocated when saving large json object to the disk

### ISSUE THREAD

**Issue by chncwang** [open-source-parsers/jsoncpp#1146]
**Describe the bug**
Though the saved file is only about 2G, the memory needed during the saving process can be more than 10G, which may cause the process to be killed because of OOM.

**To Reproduce**
1. Build a large Json::Value object containing millions of values.
2. call StreamWriter::write

**Expected behavior**
Double of the file size memory consumption is acceptable, but 4x or more is not.
Or would u mind to tell me if there is any method to work around this problem. For example, would it save memory if millions of float values are concaternated into a string, rather than organized as a json array? Thank u!

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
I am using this library to store and load json format deep learning models.

**Comment by dota17** [comment]
I think if you have a lot of deeply nested data in your large json object, it does require many many  memory, because there is a recursive process in it. and if you have millions of float values, it will call `valueToString` method to conert it to string, this process also consumes a lot of memory. If there is a way, maybe we can process our data in batches.

**Comment by cdunn2001** [comment]
It's an interesting problem, probably not something this particular library will ever be best at.
