### ISSUE TITLE
Cannot parse Json

### ISSUE THREAD

**Issue by huddhudd** [open-source-parsers/jsoncpp#1215]
Cannot parse {“A”:"黒"}

**Comment by BillyDonahue** [comment]
Please be more specific.
That's supposed to work. Do you have a minimal repro?
Can you add it to a unit test to demonstrate the failure you're seeing?

**Comment by huddhudd** [comment]
Please try parse     {“A”：“黒”} 

“黒”
There are hundreds of similar to this

**Comment by dota17** [comment]
As the prompt information showed when you open this new issue, you need to provide some key information to tell us.
These information can help us solve issue.

----------------------------------------------------------------------------------------------------------------------------------
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1.
2.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Meson version
 - Ninja version

**Additional context**
Add any other context about the problem here.

**Comment by gaozilai** [comment]
All the following Chinese characters cannot be parsed:
"黒", "玕", "盶", "砛", "芢" and so on, less than 255.
All they codes are including '0x5c'.

for example,  {"A":"芢"} , The data stream in memory is `7b 22 41 22 3a 22 c6 5c 22 7d 00`.
Originally c6 and 5c were together, now 5c and 22 are together. They become an escape character, `"` was missing.

**Comment by BillyDonahue** [comment]
I feel like this problem is understood as an encoding issue now and can be closed?
Reopen if I'm wrong.
