### ISSUE TITLE
how to build jsoncpp-1.9.4 with cmake 3.1.2?

### ISSUE THREAD

**Issue by merkey** [open-source-parsers/jsoncpp#1274]
the cmake required in jsoncpp-1.9.4 is 3.8.0, but i only have cmake-3.1.2.  is there anyway to build jsoncpp with cmake 3.1.2? 
when i removed cmake version check, more errors visible.

**Comment by cdunn2001** [comment]
One of the biggest problems with supporting **cmake** is the multitude of cmake versions and their incompatibility.

If you submit a patch that makes your cmake work without breaking newer cmakes, we would merge it. We generally follow the lead of users on cmake. Personally, I always use **meson** instead. Try it! All you need is **python**.

**Comment by baylesj** [comment]
We specifically use features from 3.8.0, which is why that is the required version. It would require removing more modern CMake patterns and features, so I'm not necessarily a fan.

+1 for using meson, or if you are stuck with CMake for whatever reason I would strongly suggest figuring out how to upgrade. 3.1.2 is from 2015, so is definitely considered old. Worst case you can use an older revision of JsonCpp if you are stuck in a legacy environment, though that is not ideal.
