### ISSUE TITLE
Not able to create ALIAS target.

### ISSUE THREAD

**Issue by ssdbest** [open-source-parsers/jsoncpp#1276]
jsoncpp 1.8.4 creates target jsoncpp_lib_static where as 1.9.4 creates jsoncpp_static. We use 1.8.4 for some platforms and 1.9.4 for some. This makes us to use if else ladder in our scripts. 
Instead we can create ALIAS using cmake add_library(jsoncpp_lib_static ALIAS jsoncpp_static) 
this is failing because jsoncpp is not creating global target.
jsoncpp should import targets with global scope.
add_library(jsoncpp_static STATIC EXPORTED GLOBAL)

**Comment by cdunn2001** [comment]
Yes, a mistake was made when the target name switched.

At any rate, if you submit a PR for make, we'd use it. We try not to touch the cmakefiles ourselves because every change seems to make one user happy but break another.

(Btw, **meson** is simpler. We have practically no support burden with **meson** and endless troubles with **cmake**.)

**Comment by SpaceIm** [comment]
@ssdbest, maybe it could help in your CMakeLists:

```cmake
find_package(jsoncpp REQUIRED CONFIG)
if(TARGET jsoncpp_static AND NOT TARGET jsoncpp_lib_static)
    add_library(jsoncpp_lib_static INTERFACE IMPORTED)
    set_property(TARGET jsoncpp_lib_static PROPERTY INTERFACE_LINK_LIBRARIES jsoncpp_static)
endif()
```

**Comment by cdunn2001** [comment]
Please submit a PR. Or see if the recent merge (#1271) will help with this.
