### ISSUE TITLE
how to compile after building with Meson and ninja

### ISSUE THREAD

**Issue by jyeric** [open-source-parsers/jsoncpp#1319]
I tried 
`g++ index.cpp -o index -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -std=c++11`  or 
`g++ index.cpp -o index -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -L /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/build-shared/libjsoncpp.so.24` or
`g++ index.cpp -o index -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -L /usr/local/lib/x8
6_64-linux-gnu/libjsoncpp.a`
and `g++ index.cpp -o index -std=c++11 -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -ljsoncpp`

But the first&second&third one replies
```
index.cpp:(.text+0x25): undefined reference to `Json::Value::Value(Json::ValueType)'
index.cpp:(.text+0x36): undefined reference to `Json::Value::Value(int)'
index.cpp:(.text+0x49): undefined reference to `Json::Value::operator[](char const*)'
index.cpp:(.text+0x5b): undefined reference to `Json::Value::operator=(Json::Value&&)'
index.cpp:(.text+0x67): undefined reference to `Json::Value::~Value()'
index.cpp:(.text+0x78): undefined reference to `Json::Value::~Value()'
index.cpp:(.text+0x9a): undefined reference to `Json::Value::~Value()'
index.cpp:(.text+0xab): undefined reference to `Json::Value::~Value()'
```
The fourth one replies
```
/usr/bin/ld: cannot find -ljsoncpp
```
how should I compile it? thx

**Comment by BillyDonahue** [comment]
> I tried
> `g++ index.cpp -o index -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -std=c++11` or

In the above example you never told g++ where the jsoncpp library was. Only the headers. So the linker errors are expected.

> `g++ index.cpp -o index -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -L /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/build-shared/libjsoncpp.so.24` or

-L is supposed to give a directory name, not the name of a library.

```
-Ldir
Add directory dir to the list of directories to be searched for -l.
```
https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Directory-Options.html#Directory-Options

> `g++ index.cpp -o index -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -L /usr/local/lib/x8 6_64-linux-gnu/libjsoncpp.a`

Same here. You're just specifying the static .a libary as if it was a directory to -L.

> and `g++ index.cpp -o index -std=c++11 -I /workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4/include -ljsoncpp`

This is closer. You have a -I (aye) giving an include directory and a `-l` ("ell") giving a the root name of a library to search for but you didn't add the -L option to find the jsoncpp library by name this way.

> But the first&second&third one replies
> 
> ```
> index.cpp:(.text+0x25): undefined reference to `Json::Value::Value(Json::ValueType)'
> index.cpp:(.text+0x36): undefined reference to `Json::Value::Value(int)'
> index.cpp:(.text+0x49): undefined reference to `Json::Value::operator[](char const*)'
> index.cpp:(.text+0x5b): undefined reference to `Json::Value::operator=(Json::Value&&)'
> index.cpp:(.text+0x67): undefined reference to `Json::Value::~Value()'
> index.cpp:(.text+0x78): undefined reference to `Json::Value::~Value()'
> index.cpp:(.text+0x9a): undefined reference to `Json::Value::~Value()'
> index.cpp:(.text+0xab): undefined reference to `Json::Value::~Value()'
> ```
> 
> The fourth one replies
> 
> ```
> /usr/bin/ld: cannot find -ljsoncpp
> ```
> 
> how should I compile it? thx

I would break it down into two steps. I find it easier to think about.
First make an `index.o`. Then, separately, link that `index.o` and some libraries (including jsoncpp) to make an executable.

    JSONCPP_DIR="/workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4"
    g++ -c index.cpp -o index.o -I $JSONCPP_DIR/include
    g++ -o index index.o $JSONCPP_DIR/build-shared/libjsoncpp.so.24

I suppose these can be combined:

    JSONCPP_DIR="/workspace/jsoncpp/jsoncpp/jsoncpp-1.9.4"
    g++ -o index index.cpp -I $JSONCPP_DIR/include $JSONCPP_DIR/build-shared/libjsoncpp.so.24

But I don't really like doing that because when something doesn't work it's harder to figure out what went wrong, as multiple steps are happening in one invocation of `g++`.

**Comment by jyeric** [comment]
thanks a lot!

**Comment by cdunn2001** [comment]
*meson* generates `jsoncpp.pc`, so you could use `pkg-config` conveniently.
