### ISSUE TITLE
[Question] Is it safe to use CharReaderBuilder and CharReader when shared linking?

### ISSUE THREAD

**Issue by a1q123456** [open-source-parsers/jsoncpp#1338]
I noticed that CharReaderBuilder::newCharReader() is returning a new-ed CharReader object pointer, which should be allocated on the heap, but I can't find any destroy method in the CharReaderBuilder.

As we know, it's unsafe to delete an object across the DLL or shared library boundary. So is it safe to use CharReaderBuilder and CharReader when linking with the shared version of jsoncpp?

**Comment by BillyDonahue** [comment]
Looks like the answer is yes.

**Comment by a1q123456** [comment]
Yes, so I think it may be a good idea to add a destroy method to CharReader and StreamWriter? @BillyDonahue

**Comment by BillyDonahue** [comment]
No destroy method. Because the allocation isn't a property of the class. It's a property of the factory. But maybe that factory should offer access to its allocator so that users can at least make intelligent unique_ptr destroy types.

Or going more ivory tower for minute, the factory could take an allocator and we would need to do a fair amount of plumbing to make sure the jsoncpp library uses the user-supplied allocator for everything.

**Comment by a1q123456** [comment]
Okay, I think that makes sense, you're right.

Since I've got the answer, I'm closing this issue.

**Comment by a1q123456** [comment]
Thank you for answering me. @BillyDonahue 

(I almost forgot that 😄)
