### ISSUE TITLE
Suggest to ::append returns boolean

### ISSUE THREAD

**Issue by wjkim00** [open-source-parsers/jsoncpp#1468]
**Is your feature request related to a problem? Please describe.**

Currently, ::append returns reference of ::Value. The std::map container's emplace() returns such as format: pair<container iterator, bool>. regardless of emplace() success or fail, the first item of pair<> is equivalent the inserting item. So we are confused the whether ::append is success or not.

**Describe the solution you'd like**

Can ::append returns value as boolean? the second item of pair<> is result that emplace() is success or not.
https://github.com/open-source-parsers/jsoncpp/blob/5defb4ed1a4293b8e2bf641e16b156fb9de498cc/src/lib_json/json_value.cpp#L1134
If can do that, We think the above line will be changed as below:
`return this->value_.map_->emplace(size(), std::move(value)).second;`
Also, return type will be changed from ::Value& to bool

**Describe alternatives you've considered**

**Additional context**

**Comment by BillyDonahue** [comment]
It's too late to change the API anyway because it would break user code, but I would also like to offer a reason why I disagree with the proposal on its technical merits.

`Value::append` is strictly an array operation. If you call it on a map-like `Value`, it will fail.
The analogy with `std::map` doesn't really apply.

The only way it fails is if the `Value` wasn't an array value or null value. The failure mode is to `throw` a `Json::LogicError` exception or crash (if no exceptions), so it will be very evident whether the append was successful. If you don't want to catch the exception or crash, you can check the type of the value before calling `append` on it.

This is more clear than returning a `bool` because it can't be missed.

The `append` function is more closely modeled on `std::vector::push_back`.

As a convenience to enable fluent chaining, it returns the `*this` reference, so you can get a value and append multiple things.

```c++
    arrayValue
        .append(123)
        .append(456)
        .append("hello");
```

**Comment by BillyDonahue** [comment]
I'm going to close the request because we can't actually change the API this way without breaking users.
Thank you for making the suggestion and thinking about this, though.
