### ISSUE TITLE
[1.9.6 regression] 'find_package(jsoncpp REQUIRED)' fails: Unknown CMake command "check_required_components"

### ISSUE THREAD

**Issue by yurivict** [open-source-parsers/jsoncpp#1568]
**Describe the bug**
```
$ cat CMakeLists.txt 
find_package(jsoncpp REQUIRED)
```

```
CMake Error at /usr/local/lib/cmake/jsoncpp/jsoncppConfig.cmake:31 (check_required_components):
  Unknown CMake command "check_required_components".
Call Stack (most recent call first):
  CMakeLists.txt:1 (find_package)
```

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.1
 - cmake-3.29.6
 - Meson version: 1.5.1

**Comment by kloczek** [comment]
It would be good to merge this PR and release new version because issue blocks other projects.

**Comment by kloczek** [comment]
Tested and with that commit it is OK now.
It would be ASP release new version.

**Comment by rpavlik** [comment]
So that does not actually fully fix the issue. Sure, it will not error immediately, but it will never set `jsoncpp_FOUND` to TRUE (or FALSE). That line in CMake calls a macro generated into that file that checks for the presence of the variables and files then sets `jsoncpp_FOUND`. Without that macro, your Meson-generated config file needs to contain other (presumably manually-written) code to perform this.
