### ISSUE TITLE
Example of jsoncpp + libcurl

### ISSUE THREAD

**Issue by cdunn2001** [open-source-parsers/jsoncpp#175]
Common question:
* http://stackoverflow.com/questions/24884490/using-libcurl-and-jsoncpp-to-parse-from-https-webserver).

**Comment by connormanning** [comment]
Self-contained example of HTTP GET via curl and JSON parse via JsonCpp: https://gist.github.com/connormanning/41efa6075515019e499c

**Comment by cdunn2001** [comment]
Thanks! Feel free to update [the wiki](https://github.com/open-source-parsers/jsoncpp/wiki) with a link to that. Or I'll do it when I have time.

**Comment by connormanning** [comment]
Added to the FAQ - [diff here](https://github.com/open-source-parsers/jsoncpp/wiki/FAQ/_compare/ccb86d20f99241508220ca75c896d88dacff9911...f39bdb29c5ed24ae02388d4f937c21026ad6d0f6?diff=split).  Also fixed a couple links that weren't formatting properly since they were Markdown format - the FAQ page is currently set to MediaWiki format.

**Comment by cdunn2001** [comment]
Sweet. Thx for fixing.

We want web-searches for 'jsoncpp libcurl' to find out page, so I'll also copy to a new wiki page of examples.

**Comment by cdunn2001** [comment]
Ah, screw it. Your way is fine. Thx.
