### ISSUE TITLE
Amalgamated Source does not include Json::Value::removeIndex() in the .h declarations

### ISSUE THREAD

**Issue by IkerGimenez** [open-source-parsers/jsoncpp#186]
With the latest source from GitHub, using the amalgamated source way of including jsoncpp into my project, the source files, specifically json.h, does not include the declaration of the function Json::Value::removeIndex. This is on Windows with Python 2.7.9.

**Comment by cdunn2001** [comment]
Hmmm. I just tried it. The pre-processor output shows:
```
   bool removeIndex(ArrayIndex i, Value* removed);
```
along with its definition later.

Which commit? Could you post the generated `json/json.h` as a github *gist*?
* https://gist.github.com/

Possibly you forgot to use `-IPATH_TO_JSON_INCLUDE_DIR` and you accidentally included `json.h` from elsewhere in your filesystem.

**Comment by IkerGimenez** [comment]
Commit 4ac4cac2bee9166e59020de73ea3f534e6ae788d, the latest one.

Here's the gist: https://gist.github.com/IkerGimenez/25d4ffb000465c44a71c
Where would I have to use -IPATH_TO_JSON_INCLUDE_DIR? In the python amalgamated.py command?

**Comment by cdunn2001** [comment]
`removeIndex()` is at [line 176](https://gist.github.com/IkerGimenez/25d4ffb000465c44a71c#file-generated-json-h-L756).

The `-I` is a compiler flag for gcc or clang. If you're using a gui like Xcode or VisualStudio, you'll have to go into the settings. The directory is the one containing `jsoncpp.cpp`. But that should be fine too since we use
```
#include "json/json.h"
```
The double-quotes (instead of angle-brackets) should avoid any problems. Could you also post a gist of `jsoncpp.cpp`?

What is the error from your compiler?

**Comment by IkerGimenez** [comment]
Wow that's embarrassing. I have no clue how that happened. I guess I incorrectly replaced one of the files. Sorry about the trouble.

**Comment by cdunn2001** [comment]
No worries!
