### ISSUE TITLE
Compiling with VS2010: warning C4018: '>' : signed/unsigned mismatch

### ISSUE THREAD

**Issue by bialix** [open-source-parsers/jsoncpp#190]
I'm using JSONCPP library from branch 0.7.1 (pre-C++11) (just to make sure I can provide to my potential users something they can use on any c++ compiler). Sources are amalgamated. While compiling in VS2010 with 3rd level of warnings I got warning 

warning C4018: '>' : signed/unsigned mismatch

That's not big deal actually and I can supress this warning in the project settings, but maybe you can/want to fix that in the sources.

Below places where that warning occurs:

bool Reader::pushError(const Value& value, const std::string& message) {
  if(value.getOffsetStart() > end_ - begin_
    || value.getOffsetLimit() > end_ - begin_)
    return false;

...

bool Reader::pushError(const Value& value, const std::string& message, const Value& extra) {
  if(value.getOffsetStart() > end_ - begin_
    || value.getOffsetLimit() > end_ - begin_
    || extra.getOffsetLimit() > end_ - begin_)
    return false;

Thank you for such good library.

**Comment by cdunn2001** [comment]
Please switch to `0.8.z`. It's still pre-C++11. It works with the same compilers as `0.7.1`. It's binary-compatible with `0.6.0-rc2`. And it has most of the bug-fixes and enhancements from `1.0.z`. Also, if you find a problem with `0.7.1`, we will not fix it within that version.

This particular problem is fixed in both those.
