### ISSUE TITLE
Keeping the order of items at toStyledString()

### ISSUE THREAD

**Issue by barneaoren** [open-source-parsers/jsoncpp#191]
The toStyledString() procedure print the json data in what looks like an alphabetic order.
It would be helpful if there will be an "original-order-preserve" option.

Thanks,
Oren

**Comment by cdunn2001** [comment]
Someday we might have an order-preserving `Value`. But that would be either a version-bump or a new symbol because we cannot break binary-compatibility in the current one.

Also, it's not clear what to do when an existing key-value pair is modified, or when one is deleted and re-added programmatically.

And there are trade-offs. Do we want O(n) in-order traversals? Minimum storage size? O(lg n) insertion?

It might be best to make the reader/writer a template, and to provide multiple `Value` types.

Anyway, it's a non-trivial amount of work.

**Comment by rickyviking** [comment]
Don't know if other people agree with what I'm saying (@barneaoren ??), but as far as I'm concerned, I wouldn't care too much about preserving the order of insertion/modification on a `Value` the way they take place during the program execution.
I'd rather like to specify somehow the property order just before writing them to stream.
Is it easier to think about an optional parameter on the `Value`to be used by (some of ) the `Writer`? Pretty much the same way as comments are handled. 
If no "ordering" param is specified or some props are missing, the standard alphabetic order would be maintained.
Ricky

**Comment by cdunn2001** [comment]
Yes, a flag to allow either alphabetical or original order would be nice.

The issue is binary-compatibility. We would need to replace `map<CZString, Value>` with an order-preserving structure of the same size. It's a lot of work. Sorry. It could be done in 2.0, when we would probably switch to a hashmap as well (instead of a red-black tree).
