### ISSUE TITLE
Json::Value::getMemberNames() returns names sorted alphabetically

### ISSUE THREAD

**Issue by craigminihan** [open-source-parsers/jsoncpp#237]
The call to getMemberNames() returns the field names sorted alphabetically and not in the order seen in the source json file. I assume this is to improve the performance of the field name lookup.

Unfortunately in some applications, eg. Apache CouchDB, the field order must be preserved for certain map/reduce operations. So turning source doc field order from C, B, A to A, B, C changes the behavior of the application if the json passes through jsoncpp.

If this is as-designed it would be useful to document this in the getMemberNames() doxygen comment block.

**Comment by BillyDonahue** [comment]
The JSON spec at http://www.json.org/ says explicitly that you can't rely on ordering in an `object`.

> An `object` is an unordered set of name/value pairs.

Unless you're given special guarantees by a library you shouldn't assume anything beyond the spec.

**Comment by craigminihan** [comment]
I guess it depends on how you interpret the word unordered. In this case the member fields are ordered explicitly by jsoncpp. It is fairly simple to 'preserve' the original field order and still retain the logN lookup.

In terms of a JS VM are the following objects the same?
```json
{ "A": 123, "B": 456 } and { "B": 456, "A": 123}
```
If the answer is yes then order truly isn't important. If the answer is no then it is. If the transport modifies the field order you could end up with different comparison results after deserialization.

My main point here is: if this behavior is by-design then a doc comment is a great move.

**Comment by BillyDonahue** [comment]
I think there's only one interpretation of the word 'unordered'. It means order doesn't matter and can't be relied on.

``` javascript
{ "A": 123, "B": 456 } and { "B": 456, "A": 123}
```

Yes, those are conceptually the same JSON object, but JS VMs are irrelevant to the JSON spec.
Proving their equality is not straightforward:
  http://stackoverflow.com/questions/201183/how-to-determine-equality-for-two-javascript-objects

Back to Jsoncpp though. I don't think it's simple to preserve order-of-appearance. It requires maintenance of a secondary structure in parallel to the map already used for lgN lookups. That's storage and complexity.

And it would start giving devs an ordering guarantee that they will start to rely on. It would be hard to get rid of that guarantee as the library develops. I think you have to assume the order is not preserved across transport. The sender and receiver can be using different libraries.

I am looking at the docs for `getMemberNames()` and I don't see an ordering guarantee.
https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/value.h#L507

**Comment by craigminihan** [comment]
Ok, so let's flip the argument. We are deserializing 100m 1000 field objects into V8. Now we know that V8 creates a new type for each unique object signature it sees. If the transport *randomly* reorders the fields in each object then we will have a major memory problem in the VM. This is in essence the same 'unordered' problem as above - it shouldn't mean game on to shuffle things around as we see fit  with no regard to downstream.

The case where the fields are ordered alphabetically is just accidentally not invoking the pathological case. However it lurks there in the wings waiting to bite.

**Comment by BillyDonahue** [comment]
I'm not sure where Jsoncpp fits into that example. If a user wants ordered keys, there's JSON array. Or if they want the objects to conform to a single type as an optimization, they could do such a conversion immediately after parsing as a fixup step. But if you're writing code that depends on preservation of object key order across machines, you're writing buggy code. It may be a little bit tough-love and sadistic, but I'd say that I'd even deliberately scramble the key order in debug builds just to be on the safe side, to ensure that users don't develop a dependency on behavior that's not guaranteed.

**Comment by cdunn2001** [comment]
This comes up from time to time. I have no real preference for ordered vs. unordered. I defer to others. Ordered is not a bad idea, but it's much more complicated than it sounds.

For example, `Json::Value` is a *dynamic* data-structure: It can be altered after it is read from some source. If you add a new key/value, should that go onto the tail of the ordered list? Ok, that sorta makes sense. But what if you alter an existing key/value? Should it keep its same spot, or pop to the tail? Whatever you pick, it's now something to document, not obvious.

But we also have a practical problem: It's hard to put an extra data-structure into `Json::Value` and maintain binary-compatibility.

Then there's configuration: In order to avoid breaking existing tests, we need to provide a way to preserve the current behavior. That means `Json::Value` requires configuration. It's easy to configure a builder, which is a temporary object, a kind of meta-data. But how would we configure `Json::Value`? What is the API? Does it go into the constructor? Does it propagate into sub-values? Is it a const setting, and if not, should be alter the order when the setting changes? Maybe it's better to have more than one Value class, and to use generics for the readers and writers.

I am open to an order-preserving Value for version 2.0, but we would need more volunteers. For 2.0, we should include a bunch of other non-backward-compatible changes as well, in the initial release. It's a lot of work. And as Billy points out, there is reason for debate.

Anyway, you can always do this:
```js
[
  ["key1", "value1"],
  ["key2", "value2"],
  ...
]
```

**Comment by cdunn2001** [comment]
@BillyDonahue, @craigminihan also asks for the alphabetization to be documented. I think that's reasonable. I'm pretty sure that @blep intended the output to be alphabetized a long time ago, and it is for all writers (since they all use `getMemberNames()`). So we might as well advertise that -- unless you object. I hate to make an unnecessary guarantee, but I also hate to imply that order might be preserved. Tests are difficult if order is not at least *repeatable*, and ideally *predictable*.

**Comment by BillyDonahue** [comment]
@cdunn2001, I don't think it's reasonable to provide a guarantee that `getMemberNames()` will be ordered, because it's a low-level member function and should be fast. `getMemberNames()` is the only way to get the member names out of a `Json::Value`, so it shouldn't have unnecessary runtime overhead.
If people are writing tests against a condition that's not guaranteed, they're writing buggy tests and they'll benefit from a breaking change. We really shouldn't tolerate a culture of golden tests locking us into a guarantee we never made. It would be better for Json::Value to store its keys as a std::unordered_map than as a std::map. Objects can get into the thousands of keys and the N*lg(N) cost to build them up can start to matter. I was actually surprised to see std::map there when I first looked into it.

I have no desire to break good tests, but if they're depending on the order of JSON object keys they are not good tests. Having predictable hashing is actually dangerous and exposes your users to [horrifying DoS attacks] (http://arstechnica.com/business/2011/12/huge-portions-of-web-vulnerable-to-hashing-denial-of-service-attack/) and worse. The unordered set ordering has to be free to change completely from one run to the next. Expose broken tests early. Rip the band-aid off.

As a [googletest] (https://code.google.com/p/googletest/) maintainer, I added the `UnorderedElementsAre` matcher and replaced hundreds of brittle `hash_map` test expectations with it. For years these tests were blocking progress in our hash algorithms. Now the hash functors can change or be randomized without breaking those tests ever again. Tests on the value of unordered containers are fine, they just need to manually apply their own sorting first, or use an order-independent matching algorithm.

How about this: `getMemberNames()` maintains exactly the same guarantees it has now. That is, it is unordered. We can also provide a `getSortedMemberNames()` that returns the same data, but sorted and, obviously from the name, is a little slower. `getSortedMemberNames()` is not necessary, but we could provide it as a convenience for people who don't want to do their own sorting.

Bad Test:
      ```EXPECT_THAT(obj.getMemberNames(), ElementsAre("a", "b", c"));```
Good Test:
      ```EXPECT_THAT(obj.getMemberNames(), WhenSorted(ElementsAre("a", "b", c")));```
Good Test (Slightly Easier):
      ```EXPECT_THAT(obj.getSortedMemberNames(), ElementsAre("a", "b", c"));```

Where:
```
    Members getSortedMemberNames() const {
      Members v = getMemberNames();
      std::sort(v.begin(), v.end();
      return v;
    }
```

Then there's a clear fix for people who have broken tests.

**Comment by cdunn2001** [comment]
Ok. I'll add a note that sorting is not guaranteed. A new method means a minor-version bump, so we can do that later. Switching to `hashmap` was a suggestion of @blep too, but we'd have to be *very* careful to maintain binary-compatibility. I'd worry most about the iterators.

> I was actually surprised to see std::map there when I first looked into it, and I guessed it was simply due to the lack of standard hash containers pre-C++11.

Long ago, I was a **jsoncpp** user with gcc-3.x, and I think that still works. At some point, we'll have to make a clean break for 1.y.z and put 0.y.z into bug-fix-only-mode. Maybe the simplest answer is to begin a `v2` branch and plan to release it later this year. Until then, we can make binary-changes to `v2` whenever we want.

> As a googletest maintainer, I added the UnorderedElementsAre matcher and replaced hundreds of brittle hash_map test expectations with it.

`UnorderedElementsAre()` is pretty sweet. Yeah, that DoS attack method came up at Amazon too; I remember it well. Btw, I've been wanting to switch **jsoncpp** to **googletest**. If you find time, feel free!

**Comment by lls2wow** [comment]
Hi @cdunn2001  ,
    Could you tell me there`s a new branch solve the order problem from now on ? I`d reather serialize a Json::Value to string like {'C':'xxxx','B':'xxxx','A':'XXXX' } not  {'A':'xxxx','B':'xxxx','C':'XXXX' } 

Thank you very much

**Comment by cdunn2001** [comment]
@lls2wow, no, sorry. (also posted as #763)

**Comment by kooscode** [comment]
Is this still an issue many years down the line?

any way to keep the order as created??

Its real PITA to scroll through a large JSON file and tie together things that was supposed to be viually together in the same area..

**Comment by rajatkhanna1994** [comment]
Hi, is there still no way to prevent alphabetical sorting and keep the order chronological? I have large Json arrays, which I wish to keep at the end of the Json object.
