### ISSUE TITLE
how read and write JSON string that are too large to fit into available memory,

### ISSUE THREAD

**Issue by linkt** [open-source-parsers/jsoncpp#253]
Json::Reader reader;  
 Json::Value root;  
if (reader.parse(str, root))  {
}

I use the code to parse the json string ,but I failed when the Json string(the size of str is 15000) is too large to fit into available memory.
ps: when the str is small ,It is OK;

**Comment by cdunn2001** [comment]
Sorry. Known problem. I did not write the original code, but I joined this project many years ago when I added the `istream` *wrapper*. Unfortunately, it's just a wrapper.

I've made this problem more obvious by calling the new classes `CharReader/CharReaderBuilder`. We need a `StreamReader` with a completely new parser. However, note that the memory required by the JSON object tree is (almost) always *greater* than the memory used by the input string. So a conventional streaming parser saves less than 1/2 the memory. What you really need is a callback-based streaming parser, which lets you decide what to do with each element as you receive it. Some XML parsers work that way.

Someday, I plan to record pointers back into the input string, in order to reduce overall memory use and to increase data-locality. That's more likely than a streaming parser for **jsoncpp**. So you'll have to look elsewhere.
