### ISSUE TITLE
pkg-config file contains incorrect path when INCLUDE_INSTALL_DIR is overriden

### ISSUE THREAD

**Issue by mgorny** [open-source-parsers/jsoncpp#279]
Long story short:

```
$ cmake .. -DJSONCPP_WITH_PKGCONFIG_SUPPORT=1 
-- JsonCpp Version: 1.6.2
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/jsoncpp-1.6.2/_build
$ grep includedir= pkg-config/jsoncpp.pc 
includedir=${prefix}/include
```

Correct so far. However, if I change `INCLUDE_INSTALL_DIR` to another name:

```
$ cmake .. -DJSONCPP_WITH_PKGCONFIG_SUPPORT=1 -DINCLUDE_INSTALL_DIR=test
-- JsonCpp Version: 1.6.2
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/jsoncpp-1.6.2/_build
$ grep includedir= pkg-config/jsoncpp.pc 
includedir=${prefix}//tmp/jsoncpp-1.6.2/_build/test
```

An absolute path with build directory is put there, after the prefix. And if I pass an absolute path:

```
$ cmake .. -DJSONCPP_WITH_PKGCONFIG_SUPPORT=1 -DINCLUDE_INSTALL_DIR=/usr/include/jsoncpp
-- JsonCpp Version: 1.6.2
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/jsoncpp-1.6.2/_build
$ grep includedir= pkg-config/jsoncpp.pc 
includedir=${prefix}//usr/include/jsoncpp
```

Then the prefix is duplicated.

**Comment by dreifachstein** [comment]
I cannot reproduce your problem with cmake 3.4, and it seems to be a cmake bug in your case.
And your fix does not interact well with CMAKE_STAGING_PREFIX.
Suppose one is compiling with CMAKE_INSTALL_PREFIX=/usr/local and CMAKE_STAGING_PREFIX=/tmp/jsoncpp. The include dir is now installed into /tmp/jsoncpp/usr/local/include instead of /tmp/jsoncpp/include, which is inconsistent with the cmake documentation. Also a windows build is broken if both CMAKE_INSTALL_PREFIX and CMAKE_STAGING_PREFIX are set to some absolute paths.

**Comment by cdunn2001** [comment]
That's from a year ago, so I don't think I can simply revert it. Can you find a fix? Note that there may have been another minor CMakeLists.txt change recently.
