### ISSUE TITLE
0.10.5 missing FastWriter fixes in 1.6.5. Releases out of sync.

### ISSUE THREAD

**Issue by ioncube** [open-source-parsers/jsoncpp#356]
Issue/request 64 in sourceforge by Jayakrishnan from 2013 was reported fixed by Chris Dunn on 2015-3-6, adding omitEndingLineFeed(). This enhancement and at least one other are in the 1.6.5 release but not the 0.10.5 release. 

It seems there may be some missing merges, with 0.10.5 and 1.6.5 now out of sync.

**Comment by cdunn2001** [comment]
First, `omitEndingLineFeed_` could not be added to 0.y.z because it breaks binary compatibility by altering the sizeof `FastWriter`.

Second, `StreamWriterBuilder` is better. Please use that new way of generating a Writer. I *think* it always omits the trailing linefeed, since you can always add it yourself.

**Comment by ioncube** [comment]
Hi

Thanks for the heads up and quick reply Chris, and for the work on the 
library.

Nick

**Comment by cdunn2001** [comment]
:heart_eyes:
