### ISSUE TITLE
Is jsoncpp thread safe??

### ISSUE THREAD

**Issue by BruceMu** [open-source-parsers/jsoncpp#361]
i find in json_reader.cpp file,there is a static variable "stackDepth_g",and will be read and write in the readValue function; If there is more than one thread call the Reader::parse(...) function, can the program run correct ?? 

would it be better to change the stackDepth_g to be a member of reader class ?

**Comment by cdunn2001** [comment]
It's true that integer increment/decrement are not atomic operations. So it's *possible* that the depth could go below zero, or could reach it maximum prematurely. Both are fine (and unlikely). `stackDepth_g` is only there to prevent maliciously constructed JSON from crashing your program. 

> would it be better to change the stackDepth_g to be a member of reader class ?

Yes! But that would not be binary-compatible.

**Comment by ya1gaurav** [comment]
can it be protected using mutex?

**Comment by cdunn2001** [comment]
A mutex would require linking with another dependency.

Look, `OurReader` use and instance variable for stack-depth, so it has no race condition. (I.e. multiple readers are fine. Reading a *single* tree is of course not thread-safe, since it mutates the tree.) `Reader` is deprecated. And I can't imagine a scenario which could evince the race condition for the non-atomic update. The most likely problem for Reader is not the race condition, but rather the logical error if 1000 Readers are used simultaneously. (The global stack-depth would be the sum of all stack-depths.) If you need simultaneously readers, use `CharReaderBuilder`.

So don't worry!
