### ISSUE TITLE
Dealing with arrays

### ISSUE THREAD

**Issue by mtangoo** [open-source-parsers/jsoncpp#362]
I have json like below. Now I want to check if given file is in array and open it. I tried get() but it does not work. this code crashes

```cpp
         std::string pluginNameStr = "DOESNOTEXIST.json";
            Json::Value p = m_jsonPlugins.get(pluginNameStr, 0);
            if(!p.empty())
            {
                ret = p.asCString();
            }
```

```javascript
{
	"plugins" : [ "/home/stefano/plugins/prefs/Git.json" ]
}
```

What is right way of dealing with arrays?

**Comment by cdunn2001** [comment]
Not sure I understand, but the whole API is here:
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html

**Comment by mtangoo** [comment]
Sorry if I didn't explain it clearly 
I have json with array in it.  I pull the array object into Value object.  Now I want to check in that array of strings if certain string exists and if it does get the value 

Jsoncpp is wonderful only lacking few things like this one :)

**Comment by mtangoo** [comment]
And I. Already read the docs many times

**Comment by cdunn2001** [comment]
[Here](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_value.html) is the most useful page.

* `isArray()` tells whether a Value is from a JSON array.
* `size()`, `get(ArrayIndex, Value)` (or `operator[](ArrayIndex)`), and `isValidIndex()` can be used to look up items in the array. (I'd avoid using *only* `operator[]()` or `get()` since they return a valid Value even when there is no element, but they're fine if you have already checked the size.)

If someone made a really great wrapper of useful functions, we'd be happy to link it from our docs.

**Comment by MartinBonner** [comment]
If you can use C++11, then something like the following should do:
````c++
bool isFileInPlugins( const Value& pluginsArray, const std::string& file)
{
    if (!pluginsArray.isArray()
        return false;

    for (const auto& el : pluginsArray)
    {
        if (el.isString() && el.asString() == file)
            return true;
    }
    return false;
}
````
If you can't use C++11, then you'll have to write the for loop with iterators and begin and end yourself.

**Comment by MartinBonner** [comment]
Ooh.  But if you are running on Windows, beware that you need to consider case insensitive comparisons for filenames.
