### ISSUE TITLE
Couldn't Value.get() be more "safe"?

### ISSUE THREAD

**Issue by ibc** [open-source-parsers/jsoncpp#400]
```c++
bool udp = root.get("udp", true).asBool();
```

The code above crashes if the given `root` JSON looks like follows:

```json
{
  "udp": "foo"
}
```

I expected that `get()` would be smart enough to detect that "udp" is not a boolean so it returns the given default value. Do I miss something?

**Comment by ibc** [comment]
So basically the only effective way of achieving this is as follows:

```c++
bool udp = true;

if (data["udp"].isBool())
  udp = data["udp"].asBool();
```

right?

**Comment by cdunn2001** [comment]
Right.

I would like to see details like this handled by global wrappers, which could be hosted here or in a project under our *org*. The basic OOP API is already so complicated.

**Comment by ibc** [comment]
The API would not change. It is just that `Json::Value::get()` would internally check whether the first type of the value indicated by the first argument matches the type of the second argument.

**Comment by cdunn2001** [comment]
The caller can check that. For simplicity, the basic API should be only things that the caller can't do easily. A layer on top of that can consolidate common usage. That reduces complexity of the basic API, making bugs less likely, making the code easier to understand, and reducing the amount of testing needed for that API.

Your code is crashing (throwing, right?) only because you've called `asBool()`. The basic API allows this usage, and there might be a good reason for it, e.g. sentinels.

**Comment by ibc** [comment]
Clear. Thanks.
