### ISSUE TITLE
Warnings about JSONCPP_OVERRIDE

### ISSUE THREAD

**Issue by jodogne** [open-source-parsers/jsoncpp#456]
Hello,

Firstly, let me thank you for creating such an useful library!

When compiling against libjsoncpp 1.7.2, I get a huge number of warnings such as the following:

```
/usr/include/jsoncpp/json/value.h:56:22: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ~Exception() throw() JSONCPP_OVERRIDE;
```

This results from the fact that my software is compiled with all warnings enabled and using the 1998 ISO C++ standard (not 2011 ISO C++). As a consequence, the "override" keyword is not available. I would suggest you to patch the definition of the macro JSONCPP_OVERRIDE in the file "include/jsoncpp/json/config.h" as follows:

```
#if defined(_MSC_VER) && _MSC_VER <= 1600 // MSVC <= 2010
# define JSONCPP_OVERRIDE
#elif (__cplusplus < 201103L)  // 1998 ISO C++
# define JSONCPP_OVERRIDE
#else  // 2011 ISO C++ or above
# define JSONCPP_OVERRIDE override
#endif
```

HTH,
Sébastien-

**Comment by cinemast** [comment]
Ah you already forwarded. Referencing from here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819971

To my knowledge, jsoncpp with version > 1.x requires at least C++ 11. I am not sure if this only applies to compiling the framework itself or also using it. Those are 2 different stories.

**Comment by cdunn2001** [comment]
Exactly. We are trying to reserve the right to use C++11 features going forward. If you find an older 1.y.z version that works for you, great. But Debian ships with C++11 gcc support, so please use it!

In other words, if you need a specific JsonCpp, then you should build and install that version. We try very hard to maintain backward-compatibility at the binary level for any bug-fixes and patches on the 0.y.z branch, for a wide variety of compilers.

But if you want the latest version -- conveniently shipped with Debian -- then you need to use the latest compiler too. "11" refers to "2011".

That said, if you can find a way to turn off `JSONCPP_OVERRIDE` for your compiler, and if everything else works for you just fine, then we would be happy to add your exception. Just understand that your compilation might someday break in other ways. (E.g. we support VS2011 for now only because it *partially* supports C++11.)

**Comment by jodogne** [comment]
Thanks for the explanation, and sorry for the noise!
