### ISSUE TITLE
Values as Int64/UInt64

### ISSUE THREAD

**Issue by sherief** [open-source-parsers/jsoncpp#457]
There doesn't seem to be a way to get 64-bit integer values from Value objects, and using the Int / UInt getters throws an out-of-range exception. Missing feature?

**Comment by ya1gaurav** [comment]
What is your test program ? Did you try Int64/UInt64 ?

**Comment by versat** [comment]
Sorry for answering to such an old issue @cdunn2001 @ya1gaurav 
But I am experiencing the same (at least I guess it is the same) issue:
For example when using `Json::CharReader::parse()` on data like this:  `"Num" : 4290772992` (which is Hex 0xFFC00000 and thus larger than int32 max) then the `Json::Value` has the value_type set to `ValueType::intValue`.
When using `Json::Value::asInt()` on a `Json::Value` with type `ValueType::intValue` and an integer like the one above (`4290772992`) then an out-of-range exception is thrown.

In https://github.com/open-source-parsers/jsoncpp/blob/94cda30dbddc1859f111848fdd05dfb85d3287c7/src/lib_json/json_value.cpp#L1262 it is checked if the range is valid for a 32 bit integer. But when parsing JSON data, the range for detecting intValue seems to be the 64 bit integer range.

My code for retrieving the value from the `Json::Value` looks like this:
```C++
void f(const Json::Value& value)
{
  MyOwnVariant vValue;
  switch (value.type())
  {
  case ValueType::booleanValue:
  {
    vValue = value.asBool();
    break;
  }
  case ValueType::intValue:
  {
    vValue = value.asInt();
    break;
  }
  case ValueType::uintValue:
  {
    vValue = value.asUInt();
    break;
  }
//... more code
  }
//... more code
}
```
Maybe this is not as intended by you/JsonCpp?
Should I use `Json::Value::asInt64()` (at least if `JSON_HAS_INT64` is defined) or `Json::Value::asLargestInt()` for `intValue`?
And similar for `uintValue`.

Are there tests for exactly such a case? I looked through the test directory but could not find such a case, but maybe I missed something.

A few details regarding my setup:
Windows/Linux 64bit, compilers are 64 bit, `JSON_HAS_INT64` is defined

Thanks for JsonCpp and any answer :-)

**Comment by versat** [comment]
In the testrunner `Json::Value::asLargestInt()` is used for `Json::intValue`, so I guess this is the correct function to use in this case: https://github.com/open-source-parsers/jsoncpp/blob/94cda30dbddc1859f111848fdd05dfb85d3287c7/src/jsontestrunner/main.cpp#L84

I would have expected that `asInt()` has the functionality of `asLargestInt()` and to retrieve explicitly a 32 bit integer that there is a function such as `asInt32()` that works like `asInt()`. But I see that this can not be changed as it would break the API compatibility.
Maybe the documentation could be improved? So one directly sees that `asInt()`/`isInt()` is only for 32 bit integers and does not correspond to the default integer size of the platform.

**Comment by cdunn2001** [comment]
We have to worry about backward compatibility, so fixing old API is difficult. I think that's why we added `asInt64()`, which hopefully works for you, yes?

For your example, you're upset that a number between 2^31 and 2^32 is out of range? But it's an int, not an unsigned. Not sure what to say about that. The implementation is the implementation.

Note that the [JSON specs](https://www.json.org/json-en.html) say absolutely nothing about the size of integer. A fully compliant JSON parser would have to parse numbers as strings and let the API decide later how to convert to whatever the user desires (possibly an unlimited integer, as in Python). This is a mistake made by most users of JSON encoding. If you want generic data, I recommend **msgpack**, which is kind of a binary JSON format but with very easy parsing and pretty good efficiency, and strict data-typing.
