### ISSUE TITLE
operator>> eats up everything after the json value

### ISSUE THREAD

**Issue by stijnfrishert** [open-source-parsers/jsoncpp#506]
I have a stream sequentially containing a json value *and something else*. Apparently parsing the json value eats up the entire stream, also characters that are not part of the json value.

    istringstream stream("[0, 1, 2] abc");
    
    Json::Value json;
    std::string str;
    stream >> json >> str;
    
    cout << str << endl; // empty!

I assume this is an oversight? Chaining `operator>>` like this is common behaviour.

Using Jsoncpp 1.7.4, pulled from Homebrew.

**Comment by cdunn2001** [comment]
Hmmm. I think that's because we have a `StreamWriter` but only a `CharReader`, not a true `StreamReader`.

There are definitely JSON libraries available which will consume only as-needed. I think you might need a different library. Sorry.

If you want to update the docs, please submit a pull-request.
