### ISSUE TITLE
Conformance report for reference

### ISSUE THREAD

**Issue by miloyip** [open-source-parsers/jsoncpp#531]
https://github.com/miloyip/nativejson-benchmark/blob/master/sample/conformance_JsonCpp%20(C%2B%2B).md

**Comment by cdunn2001** [comment]
The `FastWriter` is deprecated and should not be used.

Would you point me to the source-code so that I can submit a pull request with the new way to use this library? I have so far found this:
* https://github.com/miloyip/nativejson-benchmark/blob/master/src/tests/jsoncpptest.cpp

Is that it?

**Comment by miloyip** [comment]
Yes. That is.

**Comment by cdunn2001** [comment]
Hmm. Any idea how to avoid this? (I'm on OSX.)
```
...
Verifying taocpp/json (C++11) ... OK
Verifying tunnuz/JSON++ (C++) ... /bin/sh: line 1: 18895 Segmentation fault: 11  ./nativejson_release_x64_gmake
```

**Comment by cdunn2001** [comment]
Nvm. I removed all of `src/tests` except jsoncpp and "rapidjson*", and I was able to pass your makefile. I'll submit a pull-request soon...

**Comment by cdunn2001** [comment]
Here are the linked documents, for my reference:
* http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
* http://www.ietf.org/rfc/rfc7159.txt

I have added strict-mode rejection of extra characters in miloyip/nativejson-benchmark#64, although I disagree that the JSON spec disallows extra characters after a properly parsed document; I think that's subject to interpretation. I do see a few things we're doing wrong even after that PR:

> All characters may be 
> placed within the quotation marks except for the characters that must be  escaped: quotation mark (U+0022), 
> reverse  solidus  (U+005C),  and  the  control  characters  U+0000  to  U+001F.

So we should escape tab and linefeed when writing, and we should reject them in strict mode. Users would not be happy, I think.

And technically, we should reject `0123` in "strict" mode, because of the leading `0`. We might be able to fix that soon.

Other than that, your tests are pointing to datatype representation differences in round-trips. I'm not sure that's really part of the spec linked above, and technically no JSON parser will satisfy the spec without supporting infinitely long integers and infinitely larger floats. Well, maybe **gason**, since it does not actually convert numbers into internal representations, I think.

**Comment by miloyip** [comment]
Yes, some roundtrip tests are not required by the standard. But currently some tests are needed to evaluate the correctness of the stringify function.

I will move some controversial parts to another section, which will not be counted in the overall score.

**Comment by baylesj** [comment]
Closing, looks like this has been resolved.
