### ISSUE TITLE
compile error when compile with c++0x

### ISSUE THREAD

**Issue by acelyc111** [open-source-parsers/jsoncpp#533]
because of "other.cstr_ = nullptr; " in json_value.cpp，my compiler is gcc 4.7, nullptr is not support

**Comment by kavika13** [comment]
From the README.md:

> [JsonCpp]: http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html
> 
> ## A note on backward-compatibility
> * `1.y.z` is built with C++11.
> * `0.y.z` can be used with older compilers.
> * Major versions maintain binary-compatibility.

From what I can tell, it seems this issue is by design. You can get the current `0.y.z` version (as of me writing this) from here:

- https://github.com/open-source-parsers/jsoncpp/releases/tag/0.10.6

If you read this issue some time later, you can get the latest version by [going to the releases page](https://github.com/open-source-parsers/jsoncpp/releases), and scrolling down.

**Comment by acelyc111** [comment]
thanks
