### ISSUE TITLE
problem when parse stringValue type int/float value raise "Value is not convertible to Int/UInt"

### ISSUE THREAD

**Issue by burling** [open-source-parsers/jsoncpp#539]
such a json str:
{"int":"123, "float":"1.34", "bool":"true"}

parse as below:
  stJsonRoot.get("int", 0).asInt();
  stJsonRoot.get("float", 0.0f).asFloat();
  stJsonRoot.get("bool", false).asBool();

will all raise exception.

i think jsoncpp should convert these value.

**Comment by cdunn2001** [comment]
Is the problem in converting strings to ints and floats? That's not how JSON works. I think you need to convert those yourself.

**Comment by vladimir-kuznetsov** [comment]
> Is the problem in converting strings to ints and floats? That's not how JSON works. I think you need to convert those yourself.

but why {"name":42} is a proper string in such a case?
  Json::Value wtf;
  wtf["name"] = 42;
  if (wtf["name"].asString() == "42")
    std::cout << "WTF?\n";

**Comment by BillyDonahue** [comment]
There is an asymmetry being pointed out here.
The `asString` function will coerce any of the various numerics to string, but some types aren't coerced.

https://github.com/open-source-parsers/jsoncpp/blob/94a6220f7c738d6711d325fd29bb8a60b97fd77e/src/lib_json/json_value.cpp#L628

But the `asInt`, `asUInt`, `asFloat` etc don't perform the inverse operation of converting string to their respective return types.

I believe the `asString` type coercion is kind of a misfeature because it sets up this expectation, but it's too late to change it.

**Comment by cdunn2001** [comment]
I can't believe my comment has 7 down-votes. JSON is strongly typed. We have some helpers, and yes, as Billy says, our helpers imply that we can convert even more. But ultimately, a JSON "string" is a "string". You should not rely on the helpers, and you certainly should not complain when you mix types.

To reiterate, here are the original examples for this ticket:
```cpp
stJsonRoot.get("int", 0).asInt();
stJsonRoot.get("float", 0.0f).asFloat();
stJsonRoot.get("bool", false).asBool();
```
Those are applied to
```json
{"int":"123, "float":"1.34", "bool":"true"}
```
All three types are strings, but `get()` is called with non-string defaults. I would expect an exception to be thrown in each case. Maybe the exception should come on the `get()`, before `asXXX()`. Is that the complaint? I do not understand how anyone could argue that the above is legal code.

I would, however, expect the following to work:
```cpp
stJsonRoot.get("int", "0").asInt();
stJsonRoot.get("float", "0.0").asFloat();
stJsonRoot.get("bool", "false").asBool();
```
Does it?
