### ISSUE TITLE
Request Coding Example

### ISSUE THREAD

**Issue by samsonsite1** [open-source-parsers/jsoncpp#559]
Hello,
I would like to request a C++ coding example for beginners.

How to read in a JSON file and then modify it, either by changing an existing value, or adding something new or deleting an item, and then write out the modified JSON file, all in one go.

Forgive me, I'm somewhat confused how to do this since the JSON reader are writer are separate classes.
I need to read, modify, and write the same file.

Thanks.

**Comment by cdunn2001** [comment]
* http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html
* https://github.com/open-source-parsers/jsoncpp/wiki

I think you can add a page to the wiki if you'd like.

**Comment by samsonsite1** [comment]
Hello,
Reading and writing JSON files by themselves is easy enough.

But, the docs don't show how to modify an existing JSON file.

Would like to see coding examples:
- How to read in an existing JSON, modify it, then write it out again.
- How to change existing values
- How to delete existing items
- How to resize existing arrays (either add or delete array elements)
- etc...

**Comment by jbmonroe** [comment]
1. Read the JSON file.  (Any number of ways--I read the stream using an independent class, then submit the stream to a Json::CharReader built with Json::CharReaderBuilder.) That will give you a Json::Value instance.
2. Make changes to that Json::Value instance.
3. Use a Json::StreamWriterBuilder to create a string from your Json::Value instance.  Write that stream to  the file from which you read it.

I don't understand the issue here--this is just the same as any other read-update-write cycle code for any other sort of data.  Since you indicate that reading and writing the files is already something you can do, it seems to me that reading up on `Json::Value::removeMember/removeIndex/resize` and recalling that changing an existing value is as simple as a reassignment gets you through the other questions.

```
void updateJSON(int newValue) {
  auto jVal = readMyJSONFile(".\\myJSON.json");
  jVal["myExistingElement"] = newValue;
  writeMyJSONFile(jVal,".\\myJSON.json");
}

```
Where do you find the conceptual difficulty exists?

**Comment by cdunn2001** [comment]
I guess they want an example of modification. Feel free to update the wiki. (Just ask if you need some sort of permission.)
