### ISSUE TITLE
Json install

### ISSUE THREAD

**Issue by Kostya1** [open-source-parsers/jsoncpp#603]
Hi!
Could you describe the installation process on Windows and Linux, please? When I include json/json.h, I get compile errors like unresolved external symbol "public:__cdecl Json::Value::Value.

**Comment by billchenchina** [comment]
@cdunn2001 I am also facing the same problem,Could you describe HOW?
thx.

**Comment by cdunn2001** [comment]
I don't build on Windows. I assume cmake would work? I don't know what causes that error. If you find out, please submit a PR, even for documentation.

To see how *we* build on Windows, look at [appveyor.yml](https://github.com/open-source-parsers/jsoncpp/blob/master/appveyor.yml), which we use for continuous integration on Appveyor.

**Comment by Bishalsahoo** [comment]
For Linux just use this:
sudo apt-get install libjsoncpp-dev
and use the flag -ljsoncpp during compilation.
For Windows : I used the amalgamate.py and included the header and cpp in my project and it worked well.
Otherwise you have to have Cmake installed on windows and then build it and specify the path in the edit environment setting.
