### ISSUE TITLE
jsoncpp doesn't register itself in the CMake package registry

### ISSUE THREAD

**Issue by tambry** [open-source-parsers/jsoncpp#627]
[Package registry documentation](https://cmake.org/cmake/help/v3.5/manual/cmake-packages.7.html#package-registry)

When building with `JSONCPP_WITH_CMAKE_PACKAGE=ON`, jsoncpp should register itself in the CMake package registry using [`export(PACKAGE)`](https://cmake.org/cmake/help/v3.9/command/export.html), so it can be found using `find_package()`.

I tried to fix this, but on my installation the *jsoncppConfig.cmake* file is generated into *jsoncpp\build\CMakeFiles\Export\lib\cmake\jsoncpp*, while doing `export(PACKAGE jsoncpp)` in the root CMake build file results in the package registry entry simply pointing to the *build* directory. Unfortunately it remains unclear to me how to get the package registry entry to point to the directory containing *jsoncppConfig.cmake*.

**Comment by chuckatkins** [comment]
The use of the CMake package registry is typically discouraged (based on many conversations with CMake core developers and being a CMake developer myself).  It's one of those CMake features that seemed good at the time but in practice tends to create far more headaches than it's worth because of the ambiguity and u expected results when searching for packages due to stale and inconsistent entries that can end up in the registry.  Rather than trying to make it work the effort would be better placed removing it's use entirely in the project.

**Comment by tambry** [comment]
I wasn't aware of that. Thank you very much for the explanation. Maybe CMake's documentation should discourage this too (it currently doesn't seem to).

Since this is discouraged... What would be the suggested method to have the jsoncpp be available for the `find_package` globally?

**Comment by cdunn2001** [comment]
If you find an improvement to our cmake files, we would welcome a PR.
