### ISSUE TITLE
Allocator should be defined as template arg

### ISSUE THREAD

**Issue by Matt-Esch** [open-source-parsers/jsoncpp#681]
This library allows for the use of a secure allocator by defining the JSONCPP_STRING type. There are two main issues I see.

 - The secure allocator is not used universally for heap allocation (there are a couple of new statements littered through the code)

 - The allocator is not trivially user configurable. Rather than hard coding a flag it would probably be better to use a template. Right now I would have to replace allocator.h and compile with the secure flag to use a custom allocator.

**Comment by cdunn2001** [comment]
Those are good ideas, but I do not think we can use them in JconCpp.

> The secure allocator is not used universally for heap allocation (there are a couple of new statements littered through the code)

It's only meant to secure *data*, a specific use-case. I hestitate to change any of the "secure allocator" code because it is currently used for data-security, not something I want to break. Myself, I *never* use the "secure allocator".

> The allocator is not trivially user configurable. Rather than hard coding a flag it would probably be better to use a template. Right now I would have to replace allocator.h and compile with the secure flag to use a custom allocator.

True. But I think a template for the *Allocator* would not go far enough. A decent Json library would accept template parameters for String, Int, Float, Map, and List. Then, they would have their own allocators by construction.

My idea would be to use something like **Gason** as the parser implementation (a fast and simple parser), and to provide a framework for users to choose their own implemenations for de/serializing specific datatypes. These are not in the JSON standard, so I think it is wise to be flexible. For example, the JSON standard does not put any limits on the size of Int or Float, and user might prefer to use her own BigInt or BigFloat.

I don't have time to re-write JsonCpp the way I would like, and I don't think anyone would adopt my version if I did, since there are other reasonably flexible JSON libraries available. JsonCpp fits a particular niche. You might be able to find another library with the architecture you have in mind.
