### ISSUE TITLE
Json::CharReaderBuilder allowComments setting appears to be broken

### ISSUE THREAD

**Issue by jeffdiclemente** [open-source-parsers/jsoncpp#690]
I am using jsoncpp 0.10.6. 

After reading the jsoncpp documentation and API, I would expect the following code snippet to return false with some error string when parsing a JSON file containing comments:

```
Json::CharReaderBuilder rbuilder;
rbuilder["rejectDupKeys"] = true;
rbuilder["allowComments"] = false;
std::string errs;

Json::parseFromStream(rbuilder, jsonContent, &root, &errs);
````
In my tests, I see that it does not. The JSON parses successfully without any error returned and with a ```Json::Value``` object containing no comments.

The JSON I'm using in the test is:
```
{ /* no, no, no. */
 "bundle.name": "foo",
 "bundle.version" : "1.0.2",
 "bundle.description" : "This bundle shouldn't have comments!",
 "authors" : ["John Doe", "Douglas Reynolds", "Daniel Cannady"],
 "rating" : 5 // no comments allowed
} 
```

This is not intuitive from a user perspective. I would expect ```Json::parseFromStream``` to return ```false``` and an error message string in ```errs```. Otherwise, I don't see how the ```allowComments``` setting in ```Json::CharReaderBuilder``` is any different from setting ```collectComments``` to ```false```.

Am I doing something wrong? 
Is this really the intended behavior of ```allowComments```?

**Comment by cdunn2001** [comment]
`collectComments` causes comments to be recorded so that they can be re-emitted by the Writer.

`allowComments` makes the parsing more lenient, so that comments will not crash the parser. So it's not the same as `collectComments`.

But JsonCpp is not meant to be a JSON validator. If it's too lenient without `allowComments`, that is acceptable behavior.

Making `0.10.6` less lenient is definitely not something we can put time into. But if you have the same problem with `master` (`1.y.z`), then *maybe* we could address  it on that branch. Definitely not on `0.y.z`.
