### ISSUE TITLE
PVS Studio static analyser reports some issues

### ISSUE THREAD

**Issue by pavel-pimenov** [open-source-parsers/jsoncpp#747]
Report:
http://www.fly-server.ru/pvs-studio/jsoncpp

**Comment by cdunn2001** [comment]
Here are the 2 `High` priority warnings:

json_writer.cpp:624 | High | V730 | Not all members of a class are initialized inside the constructor. Consider inspecting: indented_.
-- | -- | -- | --
json_value.cpp:934 | High | V607 | Ownerless expression '(* this)[newSize - 1]'.
-- | -- | -- | --

I have a fix for the first, but I have no idea for the second. What is the fix for V607, and what exactly is the problem?

**Comment by pavel-pimenov** [comment]
V607 - false positive 

else if (newSize > oldSize)
(*this)[newSize - 1];  <- 

https://www.viva64.com/en/w/v607/

**Comment by cdunn2001** [comment]
Ah. I was looking at the wrong commit locally.
* https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_value.cpp#L934

**Comment by cdunn2001** [comment]
If you want to fix the lower priority warnings, go ahead.
