### ISSUE TITLE
some bug when using jsonReader.parse with some special string

### ISSUE THREAD

**Issue by linjunmian** [open-source-parsers/jsoncpp#774]
Hi ,I find a bug when using parse with some special string.My version is 1.8.1。My code is:
```cpp
//////////////////////
std::string str("->'-->`--><!--#set var=");
Json::Value body;
Json::Reader jsonReader;
bool succ = jsonReader.parse(str,body);
std::cout<<"succ = "<<succ<<"  is object = "<<body.isObject()<<std::endl;
//////////////////////
```
the out is

    succ = 1  is object = 0;

I think there is inconsistency between the return and the body.isobject.
But when I use the string like `("aaaaaaaaaaaa")`
the out is

    succ = 0  is object = 0;

So I think this inconsistency is only sent in some special circumstances.

**Comment by cdunn2001** [comment]
Try `CharReader`. (See docs.) The deprecated `Reader` is less well defined.

**Comment by dota17** [comment]
@cdunn2001 , The same inconsistency appeared on `CharReader` in my test. this may be a real bug.

**Comment by dota17** [comment]
At first, I supossed no matter `CharReader` or `Reader`, when a string is beginning with `-`, then it will be recognized as a number, and as I  made some tests, the result were beyond my expectation, I'm sure there are some problems in `readNumber()` method and `readToken` method .  

 some result are here ctreated by `CharReader`:
```c++
the input strRes : -I
* Line 1, Column 1
  Syntax error: value, object or array expected.
isobject : 0
isString : 0
isNumber : 0
isDouble : 0
isArray : 0
```
```c++
the input strRes : -i
parse OK with newCharReader
isobject : 0
isString : 0
isNumber : 1
isDouble : 1
isArray : 0
```
```c++
the input strRes : -E
* Line 1, Column 1
  '-E' is not a number.
isobject : 0
isString : 0
isNumber : 0
isDouble : 0
isArray : 0
```

```c++
the input strRes : -e
* Line 1, Column 1
  '-e' is not a number.
isobject : 0
isString : 0
isNumber : 0
isDouble : 0
isArray : 0
```

```c++
the input strRes : -a
parse OK with newCharReader
isobject : 0
isString : 0
isNumber : 1
isDouble : 1
isArray : 0
```

```c++
the input strRes : -/[]
parse OK with newCharReader
isobject : 0
isString : 0
isNumber : 1
isDouble : 1
isArray : 0
```

```c++
the input strRes : -;
parse OK with newCharReader
isobject : 0
isString : 0
isNumber : 1
isDouble : 1
isArray : 0
```

**Comment by dota17** [comment]
Sorry, I  made a mistake. 

Tips: the body is the Json::Value in above linjunmian's testcase code

Now, I don't think it is a bug. The return and the body.isobject (isint, isarray, ...) are irrelevant, so there is no consistency between them.
The return means that the final parse return of the whole input string.

If you call isNumber() in your testcase, you will find that isNumber is `true`, and the value is `0`, and the remaining chars `>...set var=` is ignored.
Here is a related issue #107 

Reader::readNumber is a method that read a valid number from token (input stream), the char '-' is valid and decode to 0. Then the method `readNumber` is returned.
The remaining chars are ignored util in method 'Reader::parse', they are read again in method `skipCommentTokens` but they are not valid comments so that ignored finally (The new feature [failIfExtra] is not include in Reader but in CharReader, so in Reader, it will not check the extra chars).

Here is my test:
```
the input strRes : ->'-->`--><!--#set var=
return : 0
isobject : 0
isString : 0
isNumber : 1
isDouble : 1
isArray : 0
asInt : 0
asString : 0
```

**Comment by dota17** [comment]
Closing. Use `failIfExtra` in `CharReader` can avoid it . 
If this issue is still relevant, please feel free to comment/reopen it.
