### ISSUE TITLE
Do not remove CMake support

### ISSUE THREAD

**Issue by navidR** [open-source-parsers/jsoncpp#780]
I wanted to ask why  would deprecate CMake support? What is your long term plan regarding CMake? I mean meson is great but let's be honest, it’s adaptation is nowhere near CMake.

Please be clear about CMake support in your documentation. What is going on with CMake and jsoncpp.

**Comment by cdunn2001** [comment]
The reason is that **cmake** has been the source of a large fraction of maintenance activity. It seems that every time someone changes something, it breaks someone else. **Meson** has proven very easy to maintain.

Cmake is not exactly *deprecated*. It's just not tested in CI anymore. If it works, it works, and we'll continue to accept pull-requests.
