### ISSUE TITLE
Unable to parse JSON value when key contains dots/periods

### ISSUE THREAD

**Issue by doomsol** [open-source-parsers/jsoncpp#931]
I'm working with JSON data that contains dots (periods) in the keys, and I don't have control of the structure.  I'm trying to find a way to parse it using jsoncpp, but I haven't been able to find documentation of that ability.  I know other JSON parsers allow you to create a literal string or encapsulate the keys in brackets to solve this issue, so I'm wondering if it's possible with jsoncpp.

Specifically, I'm using [FileMaker's JSON functions](https://fmhelp.filemaker.com/help/18/fmp/en/index.html#page/FMP_Help/json-functions.html), which are built with jsoncpp.  FileMaker says they are limited to what jsoncpp is capable of allowing, and that I should report this issue to their developer community here for further assistance and so they can update their code.

As an example, given something like:
`{
 "user": {
   "email": "myemail@email.com",
   "another param": "another value",
   "param.with.dots": "some extra value"
 }
}`

I want to access **user."param.with.dots"** or **user.[param.with.dots]** or **user.param\\.with\\.dots** to get **"some extra value"**, but it's not possible, as far as I can tell.

Thank you for your assistance.

**Comment by AbigailBuccaneer** [comment]
This is an issue with FileMaker's JSON access syntax, not with JsonCpp - with JsonCpp the syntax would be something like:

```cpp
Json::Value document;
std::cin >> document; // read some JSON document from stdin
const Json::Value& value = document["user"]["param.with.dots"];
```

Your issue here is that FileMaker forces access to JSON data via [`JSONGetElement`](https://fmhelp.filemaker.com/help/18/fmp/en/index.html#page/FMP_Help%2Fjsongetelement.html%23ww1298725), which does lookup via the `keyOrIndexOrPath` string. JsonCpp has no direct equivalent of the keyOrIndexOrPath string; it's FileMaker that's parsing that string to lookup sub-values. To fix this issue, they need to just add some escape code handling to their JSON functions, or add an extra function which returns the value of an object field with the given string as a key.

There *is* a standard for this sort of string, but neither FileMaker nor JsonCpp doesn't support it. It's called [JSON Pointer](http://rapidjson.org/md_doc_pointer.html), and for your example it'd be `"/user/param.with.dots"`.

**Comment by doomsol** [comment]
Thank you so much for the update and confirmation that it is possible within JsonCpp.  I'll pass that information along to FileMaker and see if they can update their functions.
